import { IRBranch } from "../RBranches/types";
import { IUser } from "../Users/types";

export interface IRestaurant {
  id: number;
  owner_id: number;
  name: string | null;
  slug: string | null;
  description: string | null;
  image: string | null;
  email: string | null;
  phone_number: string | null;
  alternate_phone_number: string | null;
  website_url: string | null;
  facebook_url: string | null;
  instagram_url: string | null;
  gst_number: string | null;
  status: string | null;
  rejection_reason: string | null;
  fssai_license_number: string | null;
  is_chain: boolean;
  founded_year: number | null;
  total_branches: number | null;
  cuisine_types: string | null;
  tags: string | null;
  average_rating: number;
  total_reviews: number;
  is_verified: boolean;
  approval_status: "pending" | "approved" | "rejected";
  approval_notes: string | null;
  timezone: string;
  external_integration_id: string | null;
  priority_order: number | null;
  visibility_status: "visible" | "hidden";
  cancellation_policy: string | null;
  created_at: Date;
  updated_at: Date;
  deleted_at: Date | null;
  created_by: number | null;
  updated_by: number | null;
  deleted_by: number | null;
  account_number: string | null;
  upi_id: string | null;
  swift_code: string | null;
  bank_name: string | null;
  bank_branch: string | null;
  ifsc_code: string | null;
  account_holder_name: string | null;
  branches?: IRBranch[];
  branch?  : IRBranch
  owner?: IUser;
}
