import { IRestaurant } from "../Restaurants/types";

export interface IRBranch {
  id: number;
  restaurant_id: number;
  manager_id: number;
  location: string;
  longitude: number;
  latitude: number;
  image: string;
  email: string;
  phone_number?: string;
  alternate_phone_number?: string;
  expected_delivery_time: string;
  average_price_for_one: number;
  average_price_for_two?: number;
  delivery_charge: number;
  min_order_value?: number;
  max_order_value?: number;
  packaging_charge?: number;
  rating: number;
  is_open: boolean;
  is_featured: boolean;
  is_available_for_delivery: boolean;
  is_available_for_pickup: boolean;
  is_veg_only: boolean;
  opening_time?: string;
  closing_time?: string;
  special_opening_time?: string;
  special_closing_time?: string;
  average_preparation_time?: string;
  slug?: string;
  short_description?: string;
  full_description?: string;
  gst_number?: string;
  fssai_license_number?: string;
  service_radius_km?: number;
  approval_status: "pending" | "approved" | "rejected";
  approval_notes?: string;
  cancellation_policy?: string;
  external_integration_id?: string;
  timezone: string;
  country: string;
  state: string;
  city: string;
  zip_code: string;
  landmark?: string;
  block_floor_number?: number;
  nearby_landmark?: string;
  created_at: Date;
  updated_at: Date;
  deleted_at?: Date | null;
  created_by?: number | null;
  updated_by?: number | null;
  deleted_by?: number | null;
  restaurant?: IRestaurant;
}
